DATABASE_URL = "postgresql://postgres:1234@db.hzyzqmyabfqagcxdwjti.supabase.co:5432/postgres"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6eXpxbXlhYmZxYWdjeGR3anRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NzczODYsImV4cCI6MjA3OTA1MzM4Nn0.Rsw12yoUq7Hh1GgvAIw8tCAd8z-cPVM3c8VVHw6d9HU"
SUPABASE_URL = "https://hzyzqmyabfqagcxdwjti.supabase.co"
